### ISSUE TITLE
Issue in the HowTo-flash-Intel-Management-Engine-ME-firmware repo

### ISSUE THREAD

**Issue by alexceltare2** [CHEF-KOCH/Intel-ME-Firmware-Repository#1]
In the `HowTo-flash-Intel-Management-Engine-ME-firmware` repository readme, you've mentioned that laptop models use the 5Mo firmware. This is incorrect as laptops actually use the 1.5M model. I've used MEAnalyzer on my laptop bios and the SKU is 1.5M.

**Comment by CHEF-KOCH** [comment]
I see, it's confusing. Indeed, it is.

1.5 = Consumer 
5.0 = Cooperate 

That's the universal rule.
But there are exceptions, depending on if or if not AMT (you can still flash the wrong version but some "features" are been disabled). In my case I have a HP test laptop which requires 5 M (but AMT is disabled, not via BIOS setting but within the original firmware).
